#!/usr/bin/env python3
"""
Daily Downloads Cleanup Script
==============================

Dedicated cleanup script for data/daily_downloads directory that handles:
- Original CSV files from downloads
- Mapped CSV files generated by column mapping
- Cleaned CSV files from data cleaning process
- Manifest files used for database uploads
- Archive old files and remove temporary files

This script can be run independently or integrated into the main pipeline.
"""

import json
import logging
import os
import shutil
import zipfile
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List

from rich.console import Console
from rich.panel import Panel
from rich.table import Table

console = Console()
logger = logging.getLogger(__name__)


class DailyDownloadsCleanup:
    """Cleanup manager for daily downloads directory."""

    def __init__(self, downloads_dir: str = "data/daily_downloads"):
        self.downloads_dir = Path(downloads_dir)
        self.archive_dir = self.downloads_dir / "archives"
        self.today = datetime.now().date()

        # Create archive directory if it doesn't exist
        self.archive_dir.mkdir(parents=True, exist_ok=True)

        # File retention policies (days)
        self.retention_policies = {
            "original_csv": 7,  # Original downloaded CSV files
            "mapped_csv": 3,  # Mapped CSV files for database upload
            "cleaned_csv": 1,  # Intermediate cleaned CSV files
            "manifest_json": 1,  # Upload manifest files
            "other_json": 30,  # Other JSON configuration files
            "zip_files": 3,  # ZIP archive files
            "temp_files": 0,  # Temporary files (delete immediately)
        }

    def run_cleanup(self) -> Dict:
        """Run complete cleanup process."""
        console.print(
            Panel.fit(f"🧹 Daily Downloads Cleanup - {self.today}", border_style="blue")
        )

        stats = {
            "start_time": datetime.now(),
            "files_analyzed": 0,
            "files_archived": 0,
            "files_removed": 0,
            "space_freed": 0,
            "errors": [],
        }

        try:
            # Step 1: Analyze current state
            console.print("🔍 [cyan]Analyzing current state...[/cyan]")
            analysis = self._analyze_files()
            stats.update(analysis)

            # Step 2: Archive old original CSV files
            console.print("📦 [cyan]Archiving old CSV files...[/cyan]")
            archive_stats = self._archive_old_files()
            stats["files_archived"] = archive_stats["files_archived"]
            stats["archives_created"] = archive_stats["archives_created"]

            # Step 3: Clean up processed files
            console.print("🧽 [cyan]Cleaning up processed files...[/cyan]")
            cleanup_stats = self._cleanup_processed_files()
            stats["files_removed"] += cleanup_stats["files_removed"]
            stats["space_freed"] += cleanup_stats["space_freed"]

            # Step 4: Remove temporary files
            console.print("🗑️ [cyan]Removing temporary files...[/cyan]")
            temp_stats = self._remove_temp_files()
            stats["files_removed"] += temp_stats["files_removed"]
            stats["space_freed"] += temp_stats["space_freed"]

            # Step 5: Generate report
            self._generate_cleanup_report(stats)

            stats["success"] = True
            stats["end_time"] = datetime.now()
            stats["duration"] = stats["end_time"] - stats["start_time"]

            console.print("✅ [green]Cleanup completed successfully![/green]")

        except Exception as e:
            stats["success"] = False
            stats["errors"].append(str(e))
            console.print(f"❌ [red]Cleanup failed: {e}[/red]")
            logger.exception("Cleanup failed")

        return stats

    def _analyze_files(self) -> Dict:
        """Analyze current files in the directory."""
        analysis = {
            "total_files": 0,
            "original_csv": 0,
            "mapped_csv": 0,
            "cleaned_csv": 0,
            "manifest_json": 0,
            "other_json": 0,
            "zip_files": 0,
            "temp_files": 0,
            "total_size": 0,
        }

        if not self.downloads_dir.exists():
            return analysis

        for file_path in self.downloads_dir.rglob("*"):
            if file_path.is_file():
                analysis["total_files"] += 1
                analysis["total_size"] += file_path.stat().st_size

                file_name = file_path.name

                # Categorize files
                if file_name.startswith("mapped_") and file_name.endswith(".csv"):
                    analysis["mapped_csv"] += 1
                elif file_name.startswith("cleaned_") and file_name.endswith(".csv"):
                    analysis["cleaned_csv"] += 1
                elif file_name.endswith(".csv"):
                    analysis["original_csv"] += 1
                elif "manifest" in file_name and file_name.endswith(".json"):
                    analysis["manifest_json"] += 1
                elif file_name.endswith(".json"):
                    analysis["other_json"] += 1
                elif file_name.endswith(".zip"):
                    analysis["zip_files"] += 1
                elif file_name.endswith((".tmp", ".temp", ".lock", ".partial")):
                    analysis["temp_files"] += 1

        return analysis

    def _archive_old_files(self) -> Dict:
        """Archive old original CSV files."""
        stats = {"files_archived": 0, "archives_created": 0}

        # Find original CSV files older than retention period
        old_files = []
        cutoff_date = self.today - timedelta(
            days=self.retention_policies["original_csv"]
        )

        for file_path in self.downloads_dir.rglob("*.csv"):
            # Skip mapped and cleaned files
            if file_path.name.startswith(("mapped_", "cleaned_")):
                continue

            try:
                file_date = datetime.fromtimestamp(file_path.stat().st_mtime).date()
                if file_date < cutoff_date:
                    old_files.append((file_path, file_date))
            except Exception as e:
                logger.warning(f"Error checking date for {file_path}: {e}")

        # Group files by date and create archives
        files_by_date = {}
        for file_path, file_date in old_files:
            if file_date not in files_by_date:
                files_by_date[file_date] = []
            files_by_date[file_date].append(file_path)

        for date, files in files_by_date.items():
            if files:
                archive_name = f"original_csv_{date.strftime('%Y%m%d')}.zip"
                archive_path = self.archive_dir / archive_name

                try:
                    with zipfile.ZipFile(archive_path, "w", zipfile.ZIP_DEFLATED) as zf:
                        for file_path in files:
                            rel_path = file_path.relative_to(self.downloads_dir)
                            zf.write(file_path, rel_path)
                            file_path.unlink()
                            stats["files_archived"] += 1

                    stats["archives_created"] += 1
                    console.print(
                        f"📦 Created archive: {archive_name} ({len(files)} files)"
                    )

                except Exception as e:
                    logger.error(f"Error creating archive {archive_path}: {e}")

        return stats

    def _cleanup_processed_files(self) -> Dict:
        """Clean up mapped, cleaned, and manifest files."""
        stats = {"files_removed": 0, "space_freed": 0}

        # Clean up mapped CSV files
        mapped_cutoff = self.today - timedelta(
            days=self.retention_policies["mapped_csv"]
        )
        for file_path in self.downloads_dir.glob("mapped_*.csv"):
            if self._should_remove_file(file_path, mapped_cutoff):
                size = file_path.stat().st_size
                file_path.unlink()
                stats["files_removed"] += 1
                stats["space_freed"] += size
                console.print(f"🗑️ Removed mapped file: {file_path.name}")

        # Clean up cleaned CSV files
        cleaned_cutoff = self.today - timedelta(
            days=self.retention_policies["cleaned_csv"]
        )
        for file_path in self.downloads_dir.glob("cleaned_*.csv"):
            if self._should_remove_file(file_path, cleaned_cutoff):
                size = file_path.stat().st_size
                file_path.unlink()
                stats["files_removed"] += 1
                stats["space_freed"] += size
                console.print(f"🗑️ Removed cleaned file: {file_path.name}")

        # Clean up manifest files
        manifest_cutoff = self.today - timedelta(
            days=self.retention_policies["manifest_json"]
        )
        for file_path in self.downloads_dir.glob("*manifest*.json"):
            if self._should_remove_file(file_path, manifest_cutoff):
                size = file_path.stat().st_size
                file_path.unlink()
                stats["files_removed"] += 1
                stats["space_freed"] += size
                console.print(f"🗑️ Removed manifest: {file_path.name}")

        return stats

    def _remove_temp_files(self) -> Dict:
        """Remove temporary files."""
        stats = {"files_removed": 0, "space_freed": 0}

        temp_patterns = ["*.tmp", "*.temp", "*.lock", "*.partial"]

        for pattern in temp_patterns:
            for file_path in self.downloads_dir.rglob(pattern):
                try:
                    size = file_path.stat().st_size
                    file_path.unlink()
                    stats["files_removed"] += 1
                    stats["space_freed"] += size
                    console.print(f"🗑️ Removed temp file: {file_path.name}")
                except Exception as e:
                    logger.warning(f"Error removing temp file {file_path}: {e}")

        return stats

    def _should_remove_file(self, file_path: Path, cutoff_date: datetime.date) -> bool:
        """Check if file should be removed based on cutoff date."""
        try:
            file_date = datetime.fromtimestamp(file_path.stat().st_mtime).date()
            return file_date < cutoff_date
        except Exception as e:
            logger.warning(f"Error checking date for {file_path}: {e}")
            return False

    def _generate_cleanup_report(self, stats: Dict):
        """Generate and display cleanup report."""
        table = Table(title="🧹 Cleanup Summary", border_style="green")
        table.add_column("Metric", style="cyan")
        table.add_column("Count", style="green")
        table.add_column("Details", style="white")

        table.add_row(
            "Files Analyzed",
            str(stats.get("total_files", 0)),
            "Total files in directory",
        )
        table.add_row(
            "Files Archived",
            str(stats.get("files_archived", 0)),
            "Old CSV files moved to archives",
        )
        table.add_row(
            "Files Removed",
            str(stats.get("files_removed", 0)),
            "Processed and temp files deleted",
        )
        table.add_row(
            "Archives Created",
            str(stats.get("archives_created", 0)),
            "New ZIP archives created",
        )
        table.add_row(
            "Space Freed",
            f"{stats.get('space_freed', 0) / 1024 / 1024:.1f} MB",
            "Disk space recovered",
        )

        console.print(table)

        # Display file type breakdown
        if any(key in stats for key in ["original_csv", "mapped_csv", "cleaned_csv"]):
            breakdown_table = Table(title="📊 File Type Breakdown", border_style="blue")
            breakdown_table.add_column("File Type", style="cyan")
            breakdown_table.add_column("Count", style="green")
            breakdown_table.add_column("Retention Policy", style="yellow")

            breakdown_table.add_row(
                "Original CSV",
                str(stats.get("original_csv", 0)),
                f"{self.retention_policies['original_csv']} days",
            )
            breakdown_table.add_row(
                "Mapped CSV",
                str(stats.get("mapped_csv", 0)),
                f"{self.retention_policies['mapped_csv']} days",
            )
            breakdown_table.add_row(
                "Cleaned CSV",
                str(stats.get("cleaned_csv", 0)),
                f"{self.retention_policies['cleaned_csv']} days",
            )
            breakdown_table.add_row(
                "Manifest JSON",
                str(stats.get("manifest_json", 0)),
                f"{self.retention_policies['manifest_json']} days",
            )
            breakdown_table.add_row(
                "Other JSON",
                str(stats.get("other_json", 0)),
                f"{self.retention_policies['other_json']} days",
            )
            breakdown_table.add_row(
                "ZIP Files",
                str(stats.get("zip_files", 0)),
                f"{self.retention_policies['zip_files']} days",
            )
            breakdown_table.add_row(
                "Temp Files", str(stats.get("temp_files", 0)), "Immediate removal"
            )

            console.print(breakdown_table)


def main():
    """Main cleanup execution."""
    cleanup = DailyDownloadsCleanup()
    results = cleanup.run_cleanup()

    if results["success"]:
        console.print(f"\n🎉 [green]Cleanup completed in {results['duration']}[/green]")
        return True
    else:
        console.print(
            f"\n❌ [red]Cleanup failed with {len(results['errors'])} errors[/red]"
        )
        for error in results["errors"]:
            console.print(f"   [red]• {error}[/red]")
        return False


if __name__ == "__main__":
    import logging

    logging.basicConfig(level=logging.INFO)
    success = main()
    exit(0 if success else 1)
