#!/usr/bin/env python3
"""
Database Import Script for Horse Racing AI v2.0

This script creates the PostgreSQL database schema and imports data from
the processed SQL files generated by the horseracedatabase auto-downloader.
"""

import asyncio
import logging
import sys
from pathlib import Path
from typing import List, Dict, Any
import psycopg2
from psycopg2.extensions import ISOLATION_LEVEL_AUTOCOMMIT
import os
from datetime import datetime
import glob

# Setup logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s",
    handlers=[logging.StreamHandler(), logging.FileHandler("database_import.log")],
)
logger = logging.getLogger(__name__)


class DatabaseImporter:
    """Database schema creation and data import manager"""

    def __init__(self):
        self.connection = None
        self.cursor = None
        self.data_dir = Path("data/horseracedatabase")

        # Database configuration
        self.db_config = {
            "host": "localhost",
            "port": 5433,
            "database": "horse_racing_db",
            "user": "horse_racing",
            "password": os.getenv("POSTGRES_PASSWORD", "secure_password_123"),
        }

    def connect(self):
        """Connect to PostgreSQL database"""
        try:
            logger.info("Connecting to PostgreSQL database...")
            self.connection = psycopg2.connect(**self.db_config)
            self.connection.set_isolation_level(ISOLATION_LEVEL_AUTOCOMMIT)
            self.cursor = self.connection.cursor()
            logger.info("✅ Successfully connected to database")
            return True
        except Exception as e:
            logger.error(f"❌ Failed to connect to database: {e}")
            return False

    def create_schema(self):
        """Create database schema based on the SQL data structure"""
        try:
            logger.info("Creating database schema...")

            # Create races table
            self.cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS races (
                    Race_ID INTEGER PRIMARY KEY,
                    race_number TEXT,
                    race_time TEXT,
                    course_id REAL,
                    Course TEXT,
                    Race_type TEXT,
                    Date DATE,
                    Race_name TEXT,
                    Class TEXT,
                    Years TEXT,
                    Distance TEXT,
                    Surface TEXT,
                    Prize TEXT,
                    Runners_racecard INTEGER,
                    Runners TEXT,
                    Draw TEXT,
                    EW_racecard INTEGER,
                    EW TEXT,
                    Places_EW_racecard INTEGER,
                    Places_EW TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """
            )

            # Create horses table
            self.cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS horses (
                    id INTEGER PRIMARY KEY,
                    uptodate DATE,
                    state TEXT,
                    race_id_last_race INTEGER,
                    date_last_race DATE,
                    name TEXT,
                    country TEXT,
                    age TEXT,
                    color TEXT,
                    owner TEXT,
                    sire TEXT,
                    dam TEXT,
                    dam_sire TEXT,
                    sex TEXT,
                    Total_races REAL,
                    Wins REAL,
                    Percentage_wins TEXT,
                    placed REAL,
                    Percentage_placed TEXT,
                    Flat_AW_races REAL,
                    Flat_AW_wins REAL,
                    Flat_AW_rate TEXT,
                    Flat_AW_placed REAL,
                    Flat_AW_placed_rate TEXT,
                    Flat_Turf_races REAL,
                    Flat_Turf_wins REAL,
                    Flat_Turf_rate TEXT,
                    Flat_Turf_placed REAL,
                    Flat_Turf_placed_rate TEXT,
                    Chase_races REAL,
                    Chase_wins REAL,
                    Chase_rate TEXT,
                    Chase_placed REAL,
                    Chase_placed_rate TEXT,
                    Hurdle_races REAL,
                    Hurdle_wins REAL,
                    Hurdle_rate TEXT,
                    Hurdle_placed REAL,
                    Hurdle_placed_rate TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """
            )

            # Create jockeys_stats table
            self.cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS jockeys_stats (
                    id SERIAL PRIMARY KEY,
                    jockey_name TEXT,
                    total_rides INTEGER,
                    wins INTEGER,
                    win_percentage REAL,
                    places INTEGER,
                    place_percentage REAL,
                    total_earnings TEXT,
                    avg_earnings_per_ride REAL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """
            )

            # Create trainers_stats table
            self.cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS trainers_stats (
                    id SERIAL PRIMARY KEY,
                    trainer_name TEXT,
                    total_runners INTEGER,
                    wins INTEGER,
                    win_percentage REAL,
                    places INTEGER,
                    place_percentage REAL,
                    total_earnings TEXT,
                    avg_earnings_per_runner REAL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                );
            """
            )

            # Create racecard_details table
            self.cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS racecard_details (
                    id SERIAL PRIMARY KEY,
                    race_id INTEGER,
                    horse_id INTEGER,
                    horse_name TEXT,
                    jockey TEXT,
                    trainer TEXT,
                    weight TEXT,
                    odds TEXT,
                    form TEXT,
                    age TEXT,
                    draw INTEGER,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (race_id) REFERENCES races(Race_ID),
                    FOREIGN KEY (horse_id) REFERENCES horses(id)
                );
            """
            )

            # Create records table (for results data)
            self.cursor.execute(
                """
                CREATE TABLE IF NOT EXISTS records (
                    id SERIAL PRIMARY KEY,
                    race_id INTEGER,
                    position INTEGER,
                    horse_name TEXT,
                    jockey TEXT,
                    trainer TEXT,
                    sp_odds TEXT,
                    margin TEXT,
                    time_taken TEXT,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (race_id) REFERENCES races(Race_ID)
                );
            """
            )

            # Create indexes for performance
            self.cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_races_date ON races(Date);"
            )
            self.cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_races_course ON races(Course);"
            )
            self.cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_horses_name ON horses(name);"
            )
            self.cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_racecard_race_id "
                "ON racecard_details(race_id);"
            )
            self.cursor.execute(
                "CREATE INDEX IF NOT EXISTS idx_records_race_id " "ON records(race_id);"
            )

            logger.info("✅ Database schema created successfully")
            return True

        except Exception as e:
            logger.error(f"❌ Failed to create schema: {e}")
            return False

    def find_sql_files(self) -> List[Path]:
        """Find all SQL files in the data directory"""
        sql_files = []
        for pattern in ["**/*.sql"]:
            sql_files.extend(Path(self.data_dir).glob(pattern))

        logger.info(f"Found {len(sql_files)} SQL files to import")
        return sql_files

    def import_sql_file(self, sql_file: Path) -> bool:
        """Import a single SQL file into the database"""
        try:
            logger.info(f"Importing {sql_file.name}...")

            with open(sql_file, "r") as f:
                sql_content = f.read()

            # Skip empty files
            if not sql_content.strip():
                logger.warning(f"Skipping empty file: {sql_file}")
                return True

            # Split into individual INSERT statements
            statements = [
                stmt.strip() for stmt in sql_content.split(";") if stmt.strip()
            ]

            imported_count = 0
            for statement in statements:
                if statement.upper().startswith("INSERT"):
                    try:
                        # Handle datetime.date() conversion for PostgreSQL
                        statement = statement.replace(
                            "datetime.date(", "DATE '"
                        ).replace(")", "'")
                        # Fix the closing parenthesis issue
                        statement = statement.replace("', '", "'), DATE '")
                        # Simple regex replacement for the date format
                        import re

                        statement = re.sub(
                            r"DATE \'(\d{4}), (\d{1,2}), (\d{1,2})\'",
                            r"'\1-\2-\3'",
                            statement,
                        )

                        self.cursor.execute(statement)
                        imported_count += 1
                    except Exception as e:
                        # Log the error but continue with other statements
                        logger.warning(
                            f"Failed to execute statement: {str(e)[:100]}..."
                        )
                        continue

            logger.info(f"✅ Imported {imported_count} records from {sql_file.name}")
            return True

        except Exception as e:
            logger.error(f"❌ Failed to import {sql_file}: {e}")
            return False

    def import_all_data(self):
        """Import all SQL files found in the data directory"""
        try:
            sql_files = self.find_sql_files()

            if not sql_files:
                logger.warning("No SQL files found to import")
                return False

            success_count = 0
            for sql_file in sql_files:
                if self.import_sql_file(sql_file):
                    success_count += 1

            logger.info(
                f"✅ Successfully imported {success_count}/{len(sql_files)} SQL files"
            )

            # Display summary statistics
            self.display_summary()

            return success_count > 0

        except Exception as e:
            logger.error(f"❌ Failed to import data: {e}")
            return False

    def display_summary(self):
        """Display summary statistics of imported data"""
        try:
            logger.info("=== DATABASE IMPORT SUMMARY ===")

            # Get table counts
            tables = [
                "races",
                "horses",
                "jockeys_stats",
                "trainers_stats",
                "racecard_details",
                "records",
            ]

            for table in tables:
                try:
                    self.cursor.execute(f"SELECT COUNT(*) FROM {table};")
                    count = self.cursor.fetchone()[0]
                    logger.info(f"📊 {table}: {count:,} records")
                except:
                    logger.info(f"📊 {table}: 0 records (table may not exist)")

            # Get latest race date
            try:
                self.cursor.execute("SELECT MAX(Date) FROM races;")
                latest_date = self.cursor.fetchone()[0]
                if latest_date:
                    logger.info(f"📅 Latest race date: {latest_date}")
            except:
                pass

            logger.info("=== END SUMMARY ===")

        except Exception as e:
            logger.error(f"Failed to generate summary: {e}")

    def cleanup(self):
        """Clean up database connections"""
        try:
            if self.cursor:
                self.cursor.close()
            if self.connection:
                self.connection.close()
            logger.info("Database connections closed")
        except:
            pass


def main():
    """Main execution function"""
    logger.info("🐴 Starting Horse Racing Database Import")

    importer = DatabaseImporter()

    try:
        # Connect to database
        if not importer.connect():
            sys.exit(1)

        # Create schema
        if not importer.create_schema():
            sys.exit(1)

        # Import all data
        if not importer.import_all_data():
            logger.warning("Data import completed with some issues")
        else:
            logger.info("🎉 Database import completed successfully!")

    except KeyboardInterrupt:
        logger.info("Import interrupted by user")
    except Exception as e:
        logger.error(f"Unexpected error: {e}")
    finally:
        importer.cleanup()


if __name__ == "__main__":
    main()
